#include "simulation/raycast/GridRaycastScene.h"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <limits>
namespace lacrima::sim {
void GridRaycastScene::Resize(u32 width,u32 height,bool solidBorder){m_width=width;m_height=height;m_cells.assign(static_cast<size_t>(width)*height,0);if(!solidBorder||width==0||height==0)return;for(u32 y=0;y<height;++y)for(u32 x=0;x<width;++x)if(x==0||y==0||x+1==width||y+1==height)m_cells[Index(x,y)]=1;}
void GridRaycastScene::Clear(){std::fill(m_cells.begin(),m_cells.end(),static_cast<u16>(0));}
bool GridRaycastScene::LoadAsciiFile(const std::string& path,bool solidBorder){std::ifstream input(path);if(!input)return false;std::vector<std::string> rows;std::string row;while(std::getline(input,row)){if(!row.empty()&&row.back()=='\r')row.pop_back();if(!row.empty())rows.push_back(row);}if(rows.empty())return false;const size_t width=rows.front().size();if(width==0)return false;for(const auto& line:rows)if(line.size()!=width)return false;Resize(static_cast<u32>(width),static_cast<u32>(rows.size()),solidBorder);for(u32 y=0;y<m_height;++y)for(u32 x=0;x<m_width;++x){const char cell=rows[y][x];u16 texture=0;if(cell>='1'&&cell<='9')texture=static_cast<u16>(cell-'0');else if(cell=='#')texture=1;else if(cell!='.'&&cell!=' ')return false;if(texture!=0)SetCell(static_cast<i32>(x),static_cast<i32>(y),texture);}return true;}
void GridRaycastScene::SetCell(i32 x,i32 y,u16 textureIndex){if(x<0||y<0||static_cast<u32>(x)>=m_width||static_cast<u32>(y)>=m_height)return;m_cells[Index(static_cast<u32>(x),static_cast<u32>(y))]=textureIndex;}
bool GridRaycastScene::IsSolid(i32 x,i32 y)const{return x>=0&&y>=0&&static_cast<u32>(x)<m_width&&static_cast<u32>(y)<m_height&&TextureAt(x,y)!=0;}
u16 GridRaycastScene::TextureAt(i32 x,i32 y)const{if(x<0||y<0||static_cast<u32>(x)>=m_width||static_cast<u32>(y)>=m_height)return 0;return m_cells[Index(static_cast<u32>(x),static_cast<u32>(y))];}
Raycast2DHit GridRaycastScene::Cast(f32 originX,f32 originY,f32 directionX,f32 directionY,f32 maxDistance)const{Raycast2DHit result{};if(m_width==0||m_height==0||maxDistance<=0)return result;const f32 length=std::sqrt(directionX*directionX+directionY*directionY);if(length<=std::numeric_limits<f32>::epsilon())return result;directionX/=length;directionY/=length;i32 mapX=static_cast<i32>(std::floor(originX)),mapY=static_cast<i32>(std::floor(originY));if(IsSolid(mapX,mapY)){result.hit=true;result.cellX=mapX;result.cellY=mapY;result.textureIndex=TextureAt(mapX,mapY);return result;}const f32 inf=std::numeric_limits<f32>::infinity(),deltaX=std::abs(directionX)>std::numeric_limits<f32>::epsilon()?std::abs(1.f/directionX):inf,deltaY=std::abs(directionY)>std::numeric_limits<f32>::epsilon()?std::abs(1.f/directionY):inf;const i32 stepX=directionX<0?-1:1,stepY=directionY<0?-1:1;f32 sideX=directionX<0?(originX-static_cast<f32>(mapX))*deltaX:(static_cast<f32>(mapX+1)-originX)*deltaX,sideY=directionY<0?(originY-static_cast<f32>(mapY))*deltaY:(static_cast<f32>(mapY+1)-originY)*deltaY;for(u32 step=0;step<m_width+m_height+2;++step){f32 distance=0;if(sideX<sideY){distance=sideX;sideX+=deltaX;mapX+=stepX;result.side=RaycastSide::Vertical;}else{distance=sideY;sideY+=deltaY;mapY+=stepY;result.side=RaycastSide::Horizontal;}if(distance>maxDistance||!IsSolid(mapX,mapY))continue;result.hit=true;result.distance=distance;result.worldX=originX+directionX*distance;result.worldY=originY+directionY*distance;result.cellX=mapX;result.cellY=mapY;result.textureIndex=TextureAt(mapX,mapY);const f32 wallCoordinate=result.side==RaycastSide::Vertical?result.worldY:result.worldX;result.wallU=std::clamp(wallCoordinate-std::floor(wallCoordinate),0.f,1.f);return result;}return result;}
std::vector<Raycast2DHit> GridRaycastScene::CastColumns(f32 ox,f32 oy,f32 dx,f32 dy,f32 px,f32 py,u32 count,f32 maxDistance)const{std::vector<Raycast2DHit> columns(count);for(u32 column=0;column<count;++column){const f32 cameraX=2.f*(static_cast<f32>(column)+.5f)/static_cast<f32>(count)-1.f;columns[column]=Cast(ox,oy,dx+px*cameraX,dy+py*cameraX,maxDistance);}return columns;}
}
